# Start with the Python 3.8 slim image as the base
FROM python:3.8-slim as builder 
# set the working directory in the container
WORKDIR /app
#
FROM builder
# copy the dependencies file to the working directory
COPY requirements.txt .
# Install the Python dependencies from the requirements.txt file
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y ca-certificates

ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt 
# copy the content of the templates directory to the working directory
COPY / .
# Expose a port to communicate with the React app
EXPOSE 8000
#
CMD [ "python", "./main.py"]


